version: 2
builds:
- id: llm-gateway-darwin-amd64
  main: ./cmd/llm-gateway
  binary: llm-gateway
  ldflags:
    - -s -w
    - -X github.com/openziti/llm-gateway/build.Version={{.Tag}}
    - -X github.com/openziti/llm-gateway/build.Hash={{.ShortCommit}}
    - -X github.com/openziti/llm-gateway/build.Date={{.Date}}
    - -X github.com/openziti/llm-gateway/build.BuiltBy=goreleaser
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64

- id: llm-gateway-darwin-arm64
  main: ./cmd/llm-gateway
  binary: llm-gateway
  ldflags:
    - -s -w
    - -X github.com/openziti/llm-gateway/build.Version={{.Tag}}
    - -X github.com/openziti/llm-gateway/build.Hash={{.ShortCommit}}
    - -X github.com/openziti/llm-gateway/build.Date={{.Date}}
    - -X github.com/openziti/llm-gateway/build.BuiltBy=goreleaser
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - arm64
